# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SpoolResource(Model):
    """A class representing a Spool service resource.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar id: Fully qualified resource ID for the resource.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the service - e.g. "Microsoft.SpoolService/spools"
    :vartype type: str
    :param location: The Azure location where the Spool service is running.
    :type location: str
    :param tags: Tags of the service which is a list of key value pairs that
     describe the resource.
    :type tags: dict[str, str]
    :ivar provisioning_state: Provisioning state of the resource. Possible
     values include: 'Unknown', 'Succeeded', 'Failed', 'Canceled', 'Running',
     'Creating', 'Updating', 'Deleting', 'Moving'
    :vartype provisioning_state: str or
     ~azure.management.spool.models.ProvisioningState
    :ivar host_name: FQDN of the Spool service instance. Format:
     xxx.westus2.service.Spool.net
    :vartype host_name: str
    :ivar version: Version of the Spool resource. Probably you need the same
     or higher version of client SDKs.
    :vartype version: str
    :param optional_features: Features that may optionally be enabled on a
     Spool instance.
    :type optional_features: list[str or
     ~azure.management.spool.models.OptionalFeature]
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
        'provisioning_state': {'readonly': True},
        'host_name': {'readonly': True},
        'version': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'tags': {'key': 'tags', 'type': '{str}'},
        'provisioning_state': {'key': 'properties.provisioningState', 'type': 'str'},
        'host_name': {'key': 'properties.hostName', 'type': 'str'},
        'version': {'key': 'properties.version', 'type': 'str'},
        'optional_features': {'key': 'properties.optionalFeatures', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(SpoolResource, self).__init__(**kwargs)
        self.id = None
        self.name = None
        self.type = None
        self.location = kwargs.get('location', None)
        self.tags = kwargs.get('tags', None)
        self.provisioning_state = None
        self.host_name = None
        self.version = None
        self.optional_features = kwargs.get('optional_features', None)
